# Generated by Django 6.0 on 2026-01-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_created_at_jobs_price_jobs_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
