# Generated by Django 6.0 on 2026-01-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobs_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/'),
        ),
    ]
